"""Selection heuristics and round-trip Compose override generation."""

from __future__ import annotations

import re
import shutil
import tempfile
from collections.abc import MutableMapping, MutableSequence
from dataclasses import dataclass
from io import StringIO
from pathlib import Path
from typing import Any

import click
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

from .compose import declared_ports

DNS_SAFE_PROJECT = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")
HTTP_PORT_PREFERENCE = {
    80: 100,
    8000: 95,
    8080: 90,
    3000: 85,
    5000: 80,
    4000: 75,
    4200: 70,
    5173: 65,
    5174: 64,
    8888: 60,
}
SERVICE_NAME_PREFERENCE = {
    "web": 100,
    "app": 90,
    "api": 80,
    "server": 70,
    "backend": 60,
}
INFRASTRUCTURE_NAMES = {
    "beat",
    "cache",
    "celery",
    "db",
    "database",
    "mailpit",
    "mysql",
    "postgres",
    "rabbitmq",
    "redis",
    "worker",
}
HOST_BRIDGE_IMAGE = "caddy:2.11.4-alpine"


@dataclass(frozen=True)
class Candidate:
    name: str
    service: dict[str, Any]
    ports: tuple[int, ...]
    score: int


def validate_project_name(model: dict[str, Any]) -> str:
    project_name = str(model.get("name") or "")
    validate_project_name_value(project_name)
    return project_name


def validate_project_name_value(project_name: str) -> None:
    if not DNS_SAFE_PROJECT.fullmatch(project_name):
        raise click.ClickException(
            f"derived project name '{project_name}' is not DNS-safe; set a safe, "
            "unique COMPOSE_PROJECT_NAME in .env first"
        )


def rank_services(model: dict[str, Any], project_name: str) -> list[Candidate]:
    services = model.get("services") or {}
    if not services:
        raise click.ClickException("the Compose project defines no services")

    candidates = []
    for name, service in services.items():
        ports = tuple(declared_ports(service))
        candidates.append(
            Candidate(
                name=name,
                service=service,
                ports=ports,
                score=_service_score(name, ports, project_name),
            )
        )
    return sorted(candidates, key=lambda candidate: (-candidate.score, candidate.name))


def choose_port(candidate: Candidate, requested: int | None) -> int | None:
    if requested is not None:
        return requested
    if len(candidate.ports) == 1:
        return candidate.ports[0]
    if not candidate.ports:
        return None

    ranked = sorted(
        candidate.ports,
        key=lambda port: (-HTTP_PORT_PREFERENCE.get(port, 0), port),
    )
    best_preference = HTTP_PORT_PREFERENCE.get(ranked[0], 0)
    if best_preference and (
        len(ranked) == 1 or HTTP_PORT_PREFERENCE.get(ranked[1], 0) < best_preference
    ):
        return ranked[0]
    return None


def create_override(
    project_name: str,
    candidate: Candidate,
    port: int,
) -> CommentedMap:
    document = CommentedMap()
    document.yaml_set_start_comment(
        "Generated by local-dev-proxy. Keep this local unless the team "
        "wants to share it."
    )
    service = CommentedMap()
    service["networks"] = CommentedMap.fromkeys(_network_names(candidate.service), None)
    service["labels"] = CommentedSeq(
        _dynamic_labels(project_name, candidate.name, port).values()
    )
    document["services"] = CommentedMap({candidate.name: service})
    document["networks"] = CommentedMap(
        {"local-dev-proxy": CommentedMap({"external": True})}
    )
    return document


def create_dockerfile_compose(service_name: str, port: int) -> CommentedMap:
    """Create a Compose project for an application built from this directory."""
    candidate = Candidate(
        name=service_name,
        service={"networks": {"default": None}},
        ports=(port,),
        score=0,
    )
    document = create_override("project", candidate, port)
    service = document["services"][service_name]
    service.insert(0, "build", ".")
    service.insert(1, "expose", CommentedSeq([str(port)]))
    document.yaml_set_start_comment(
        "Generated by local-dev-proxy from the Dockerfile in this directory."
    )
    return document


def create_host_bridge_compose(service_name: str, host_port: int) -> CommentedMap:
    """Create a Compose bridge from Traefik to a host-native HTTP process."""
    candidate = Candidate(
        name=service_name,
        service={"networks": {"local-dev-proxy": None}},
        ports=(8080,),
        score=0,
    )
    document = create_override("project", candidate, 8080)
    service = document["services"][service_name]
    service.insert(0, "image", HOST_BRIDGE_IMAGE)
    service.insert(
        1,
        "command",
        CommentedSeq(
            [
                "caddy",
                "reverse-proxy",
                "--from",
                ":8080",
                "--to",
                f"http://host.docker.internal:{host_port}",
            ]
        ),
    )
    service.insert(
        2,
        "extra_hosts",
        CommentedSeq(["host.docker.internal:host-gateway"]),
    )
    service.insert(3, "restart", "unless-stopped")
    document.yaml_set_start_comment(
        "Generated by local-dev-proxy for an HTTP application running on the host.\n"
        "The host process must listen on a Docker-reachable interface such as 0.0.0.0."
    )
    return document


def extend_override(
    document: CommentedMap,
    model: dict[str, Any],
    project_name: str,
    candidate: Candidate,
    port: int,
) -> bool:
    """Extend an existing override, raising on semantic collisions."""
    changed = False
    networks = model.get("networks") or {}
    proxy_network = networks.get("local-dev-proxy")
    if proxy_network is not None and not proxy_network.get("external", False):
        raise click.ClickException(
            "the existing local-dev-proxy network is not external; "
            "refusing to change it"
        )

    desired_resolved = _resolved_labels(project_name, candidate.name, port)
    resolved_service = (model.get("services") or {}).get(candidate.name, {})
    existing_resolved = resolved_service.get("labels") or {}
    if not isinstance(existing_resolved, dict):
        existing_resolved = {}

    for key, value in desired_resolved.items():
        if key in existing_resolved and str(existing_resolved[key]) != value:
            raise click.ClickException(
                f"existing label '{key}' conflicts with the generated value"
            )

    desired_rule_key = next(key for key in desired_resolved if key.endswith(".rule"))
    desired_rule = desired_resolved[desired_rule_key]
    for key, value in existing_resolved.items():
        if (
            key.endswith(".rule")
            and str(value) == desired_rule
            and key != desired_rule_key
        ):
            raise click.ClickException(
                f"existing router label '{key}' already uses {desired_rule}"
            )

    services = document.setdefault("services", CommentedMap())
    if not isinstance(services, MutableMapping):
        raise click.ClickException("existing override 'services' must be a mapping")
    service = services.setdefault(candidate.name, CommentedMap())
    if not isinstance(service, MutableMapping):
        raise click.ClickException(
            f"existing override service '{candidate.name}' must be a mapping"
        )

    service_networks = service.get("networks")
    if service_networks is None:
        service["networks"] = CommentedMap.fromkeys(
            _network_names(candidate.service), None
        )
        changed = True
    elif isinstance(service_networks, MutableSequence):
        if "local-dev-proxy" not in service_networks:
            service_networks.append("local-dev-proxy")
            changed = True
    elif isinstance(service_networks, MutableMapping):
        if "local-dev-proxy" not in service_networks:
            service_networks["local-dev-proxy"] = None
            changed = True
    else:
        raise click.ClickException(
            f"existing networks for service '{candidate.name}' cannot be "
            "extended safely"
        )

    labels = service.get("labels")
    missing_resolved = [key for key in desired_resolved if key not in existing_resolved]
    if labels is None:
        service["labels"] = CommentedSeq(
            _dynamic_labels(project_name, candidate.name, port)[key]
            for key in missing_resolved
        )
        changed = changed or bool(missing_resolved)
    elif isinstance(labels, MutableSequence):
        dynamic = _dynamic_labels(project_name, candidate.name, port)
        labels.extend(dynamic[key] for key in missing_resolved)
        changed = changed or bool(missing_resolved)
    elif isinstance(labels, MutableMapping):
        for key in missing_resolved:
            labels[key] = desired_resolved[key]
            changed = True
    else:
        raise click.ClickException(
            f"existing labels for service '{candidate.name}' cannot be extended safely"
        )

    top_networks = document.setdefault("networks", CommentedMap())
    if not isinstance(top_networks, MutableMapping):
        raise click.ClickException("existing override 'networks' must be a mapping")
    if "local-dev-proxy" not in top_networks:
        top_networks["local-dev-proxy"] = CommentedMap({"external": True})
        changed = True

    return changed


def load_override(path: Path) -> CommentedMap:
    yaml = _yaml()
    with path.open(encoding="utf-8") as override_file:
        document = yaml.load(override_file) or CommentedMap()
    if not isinstance(document, CommentedMap):
        raise click.ClickException(f"existing '{path}' must contain a YAML mapping")
    return document


def render_override(document: CommentedMap) -> str:
    output = StringIO()
    _yaml().dump(document, output)
    return output.getvalue()


def write_new(path: Path, document: CommentedMap) -> None:
    path.write_text(render_override(document), encoding="utf-8")


def write_extended(path: Path, document: CommentedMap) -> Path:
    backup = _next_backup(path)
    shutil.copy2(path, backup)
    rendered = render_override(document)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        delete=False,
    ) as temporary_file:
        temporary_file.write(rendered)
        temporary_path = Path(temporary_file.name)
    temporary_path.replace(path)
    return backup


def _service_score(name: str, ports: tuple[int, ...], project_name: str) -> int:
    normalized_name = name.lower()
    tokens = set(re.split(r"[._-]+", normalized_name))
    score = 50 if ports else 0
    if normalized_name == project_name:
        score += 150
    score += SERVICE_NAME_PREFERENCE.get(normalized_name, 0)
    score += max(
        (
            preference // 3
            for token, preference in SERVICE_NAME_PREFERENCE.items()
            if token in tokens
        ),
        default=0,
    )
    if normalized_name in INFRASTRUCTURE_NAMES:
        score -= 100
    if any(port in HTTP_PORT_PREFERENCE for port in ports):
        score += 25
    return score


def _network_names(service: dict[str, Any]) -> list[str]:
    networks = list((service.get("networks") or {"default": None}).keys())
    return [name for name in networks if name != "local-dev-proxy"] + [
        "local-dev-proxy"
    ]


def _object_names(project: str, service: str) -> tuple[str, str]:
    role = re.sub(r"[^a-z0-9-]+", "-", service.lower()).strip("-") or "web"
    return f"{project}-{role}", role


def _resolved_labels(project: str, service: str, port: int) -> dict[str, str]:
    object_name, _ = _object_names(project, service)
    return {
        "traefik.enable": "true",
        "traefik.docker.network": "local-dev-proxy",
        f"traefik.http.routers.{object_name}.entrypoints": "web",
        f"traefik.http.routers.{object_name}.rule": f"Host(`{project}.localhost`)",
        f"traefik.http.routers.{object_name}.service": object_name,
        f"traefik.http.services.{object_name}.loadbalancer.server.port": str(port),
    }


def _dynamic_labels(project: str, service: str, port: int) -> dict[str, str]:
    resolved = _resolved_labels(project, service, port)
    _, role = _object_names("project", service)
    object_name = f"${{COMPOSE_PROJECT_NAME}}-{role}"
    values = [
        "traefik.enable=true",
        "traefik.docker.network=local-dev-proxy",
        (f"traefik.http.routers.{object_name}.entrypoints=web"),
        (
            f"traefik.http.routers.{object_name}.rule="
            "Host(`${COMPOSE_PROJECT_NAME}.localhost`)"
        ),
        (f"traefik.http.routers.{object_name}.service={object_name}"),
        (f"traefik.http.services.{object_name}.loadbalancer.server.port={port}"),
    ]
    return dict(zip(resolved, values, strict=True))


def _yaml() -> YAML:
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)
    return yaml


def _next_backup(path: Path) -> Path:
    candidate = path.with_name(f"{path.name}.bak")
    counter = 1
    while candidate.exists():
        candidate = path.with_name(f"{path.name}.bak.{counter}")
        counter += 1
    return candidate
