"""Selection heuristics and round-trip Compose override generation."""

from __future__ import annotations

import re
import shutil
import tempfile
from collections.abc import MutableMapping, MutableSequence
from dataclasses import dataclass
from io import StringIO
from pathlib import Path
from typing import Any

import click
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq
from ruamel.yaml.error import YAMLError

from .compose import declared_ports

PROXY_NETWORK = "localghost"

DNS_SAFE_PROJECT = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")
HTTP_PORT_PREFERENCE = {
    80: 100,
    8000: 95,
    8080: 90,
    3000: 85,
    5000: 80,
    4000: 75,
    4200: 70,
    5173: 65,
    5174: 64,
    8888: 60,
}
SERVICE_NAME_PREFERENCE = {
    "web": 100,
    "app": 90,
    "api": 80,
    "server": 70,
    "backend": 60,
}
INFRASTRUCTURE_NAMES = {
    "beat",
    "cache",
    "celery",
    "db",
    "database",
    "mailpit",
    "mysql",
    "postgres",
    "rabbitmq",
    "redis",
    "worker",
}
HOST_BRIDGE_IMAGE = "caddy:2.11.4-alpine"


@dataclass(frozen=True)
class Candidate:
    name: str
    service: dict[str, Any]
    ports: tuple[int, ...]
    score: int


def validate_project_name(model: dict[str, Any]) -> str:
    project_name = str(model.get("name") or "")
    validate_project_name_value(project_name)
    return project_name


def validate_project_name_value(project_name: str) -> None:
    if not DNS_SAFE_PROJECT.fullmatch(project_name):
        raise click.ClickException(
            f"derived project name '{project_name}' is not DNS-safe; set a safe, "
            "unique COMPOSE_PROJECT_NAME in .env first"
        )


def rank_services(model: dict[str, Any], project_name: str) -> list[Candidate]:
    services = model.get("services") or {}
    if not services:
        raise click.ClickException("the Compose project defines no services")

    candidates = []
    for name, service in services.items():
        ports = tuple(declared_ports(service))
        candidates.append(
            Candidate(
                name=name,
                service=service,
                ports=ports,
                score=_service_score(name, ports, project_name),
            )
        )
    return sorted(candidates, key=lambda candidate: (-candidate.score, candidate.name))


def choose_port(candidate: Candidate, requested: int | None) -> int | None:
    if requested is not None:
        return requested
    if len(candidate.ports) == 1:
        return candidate.ports[0]
    if not candidate.ports:
        return None

    ranked = sorted(
        candidate.ports,
        key=lambda port: (-HTTP_PORT_PREFERENCE.get(port, 0), port),
    )
    best_preference = HTTP_PORT_PREFERENCE.get(ranked[0], 0)
    if best_preference and (
        len(ranked) == 1 or HTTP_PORT_PREFERENCE.get(ranked[1], 0) < best_preference
    ):
        return ranked[0]
    return None


def create_override(
    project_name: str,
    candidate: Candidate,
    port: int,
) -> CommentedMap:
    document = CommentedMap()
    document.yaml_set_start_comment(
        "Generated by localghost. Keep this local unless the team "
        "wants to share it."
    )
    service = CommentedMap()
    service["networks"] = CommentedMap.fromkeys(_network_names(candidate.service), None)
    service["labels"] = CommentedSeq(
        _dynamic_labels(project_name, candidate.name, port).values()
    )
    document["services"] = CommentedMap({candidate.name: service})
    document["networks"] = CommentedMap(
        {PROXY_NETWORK: CommentedMap({"external": True})}
    )
    return document


def create_dockerfile_compose(service_name: str, port: int) -> CommentedMap:
    """Create a Compose project for an application built from this directory."""
    candidate = Candidate(
        name=service_name,
        service={"networks": {"default": None}},
        ports=(port,),
        score=0,
    )
    document = create_override("project", candidate, port)
    service = document["services"][service_name]
    service.insert(0, "build", ".")
    service.insert(1, "expose", CommentedSeq([str(port)]))
    document.yaml_set_start_comment(
        "Generated by localghost from the Dockerfile in this directory."
    )
    return document


def create_host_bridge_compose(service_name: str, host_port: int) -> CommentedMap:
    """Create a Compose bridge from Traefik to a host-native HTTP process."""
    candidate = Candidate(
        name=service_name,
        service={"networks": {PROXY_NETWORK: None}},
        ports=(8080,),
        score=0,
    )
    document = create_override("project", candidate, 8080)
    service = document["services"][service_name]
    service.insert(0, "image", HOST_BRIDGE_IMAGE)
    service.insert(
        1,
        "command",
        CommentedSeq(
            [
                "caddy",
                "reverse-proxy",
                "--from",
                ":8080",
                "--to",
                f"http://host.docker.internal:{host_port}",
            ]
        ),
    )
    service.insert(
        2,
        "extra_hosts",
        CommentedSeq(["host.docker.internal:host-gateway"]),
    )
    service.insert(3, "restart", "unless-stopped")
    document.yaml_set_start_comment(
        "Generated by localghost for an HTTP application running on the host.\n"
        "The host process must listen on a Docker-reachable interface such as 0.0.0.0."
    )
    return document


def extend_override(
    document: CommentedMap,
    model: dict[str, Any],
    project_name: str,
    candidate: Candidate,
    port: int,
) -> bool:
    """Extend an existing override, raising on semantic collisions."""
    desired_resolved = _resolved_labels(project_name, candidate.name, port)
    validate_proxy_configuration(model, project_name, candidate, port)

    services = document.get("services", CommentedMap())
    if not isinstance(services, MutableMapping):
        raise click.ClickException("existing override 'services' must be a mapping")
    service = services.get(candidate.name, CommentedMap())
    if not isinstance(service, MutableMapping):
        raise click.ClickException(
            f"existing override service '{candidate.name}' must be a mapping"
        )

    service_networks = service.get("networks")
    if service_networks is not None and not isinstance(
        service_networks, (MutableMapping, MutableSequence)
    ):
        raise click.ClickException(
            f"existing networks for service '{candidate.name}' cannot be "
            "extended safely"
        )

    labels = service.get("labels")
    if labels is not None and not isinstance(labels, (MutableMapping, MutableSequence)):
        raise click.ClickException(
            f"existing labels for service '{candidate.name}' cannot be extended safely"
        )

    top_networks = document.get("networks", CommentedMap())
    if not isinstance(top_networks, MutableMapping):
        raise click.ClickException("existing override 'networks' must be a mapping")
    if PROXY_NETWORK in top_networks and not _external_network(
        top_networks[PROXY_NETWORK]
    ):
        raise click.ClickException(
            f"the existing {PROXY_NETWORK} network is not external or does not "
            "use the fixed name; refusing to change it"
        )

    document_labels = _document_labels(document, project_name)
    _validate_label_collisions(document_labels, desired_resolved, candidate.name)
    all_labels = (*_model_labels(model), *document_labels)
    existing_resolved = {
        key
        for service_name, key, value in all_labels
        if service_name == candidate.name
        and key in desired_resolved
        and value == desired_resolved[key]
    }
    missing_resolved = [key for key in desired_resolved if key not in existing_resolved]

    changed = False
    if "services" not in document:
        document["services"] = services
        changed = True
    if candidate.name not in services:
        services[candidate.name] = service
        changed = True

    if service_networks is None:
        service["networks"] = CommentedMap.fromkeys(
            _network_names(candidate.service), None
        )
        changed = True
    elif isinstance(service_networks, MutableSequence):
        if PROXY_NETWORK not in service_networks:
            service_networks.append(PROXY_NETWORK)
            changed = True
    elif PROXY_NETWORK not in service_networks:
        service_networks[PROXY_NETWORK] = None
        changed = True

    if labels is None:
        service["labels"] = CommentedSeq(
            _dynamic_labels(project_name, candidate.name, port)[key]
            for key in missing_resolved
        )
        changed = changed or bool(missing_resolved)
    elif isinstance(labels, MutableSequence):
        dynamic = _dynamic_labels(project_name, candidate.name, port)
        labels.extend(dynamic[key] for key in missing_resolved)
        changed = changed or bool(missing_resolved)
    else:
        for key in missing_resolved:
            labels[key] = desired_resolved[key]
            changed = True

    if "networks" not in document:
        document["networks"] = top_networks
        changed = True
    if PROXY_NETWORK not in top_networks:
        top_networks[PROXY_NETWORK] = CommentedMap({"external": True})
        changed = True

    return changed


def load_override(path: Path) -> CommentedMap:
    yaml = _yaml()
    try:
        with path.open(encoding="utf-8") as override_file:
            document = yaml.load(override_file) or CommentedMap()
    except YAMLError as exc:
        raise click.ClickException(
            f"existing '{path}' is not valid YAML: {exc}"
        ) from exc
    except (OSError, UnicodeError) as exc:
        raise click.ClickException(f"could not read existing '{path}': {exc}") from exc
    if not isinstance(document, CommentedMap):
        raise click.ClickException(f"existing '{path}' must contain a YAML mapping")
    return document


def render_override(document: CommentedMap) -> str:
    output = StringIO()
    _yaml().dump(document, output)
    return output.getvalue()


def write_new(path: Path, document: CommentedMap) -> None:
    rendered = render_override(document)
    try:
        with path.open("x", encoding="utf-8") as output_file:
            output_file.write(rendered)
    except FileExistsError as exc:
        raise click.ClickException(f"refusing to overwrite existing '{path}'") from exc
    except OSError as exc:
        raise click.ClickException(f"could not write '{path}': {exc}") from exc


def write_extended(path: Path, document: CommentedMap) -> Path:
    if path.is_symlink():
        raise click.ClickException(f"refusing to replace symlink '{path}'")
    rendered = render_override(document)
    backup = _next_backup(path)
    temporary_path: Path | None = None
    try:
        shutil.copy2(path, backup)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as temporary_file:
            temporary_file.write(rendered)
            temporary_path = Path(temporary_file.name)
        shutil.copymode(path, temporary_path)
        temporary_path.replace(path)
        temporary_path = None
    except OSError as exc:
        raise click.ClickException(f"could not safely update '{path}': {exc}") from exc
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
    return backup


def validate_proxy_configuration(
    model: dict[str, Any],
    project_name: str,
    candidate: Candidate,
    port: int,
) -> None:
    """Refuse model settings that would collide with generated proxy settings."""
    networks = model.get("networks") or {}
    proxy_network = networks.get(PROXY_NETWORK)
    if PROXY_NETWORK in networks and not _external_network(proxy_network):
        raise click.ClickException(
            f"the existing {PROXY_NETWORK} network is not external or does not "
            "use the fixed name; refusing to change it"
        )

    _validate_label_collisions(
        _model_labels(model),
        _resolved_labels(project_name, candidate.name, port),
        candidate.name,
    )


def _service_score(name: str, ports: tuple[int, ...], project_name: str) -> int:
    normalized_name = name.lower()
    tokens = set(re.split(r"[._-]+", normalized_name))
    score = 50 if ports else 0
    if normalized_name == project_name:
        score += 150
    score += SERVICE_NAME_PREFERENCE.get(normalized_name, 0)
    score += max(
        (
            preference // 3
            for token, preference in SERVICE_NAME_PREFERENCE.items()
            if token in tokens
        ),
        default=0,
    )
    if normalized_name in INFRASTRUCTURE_NAMES:
        score -= 100
    if any(port in HTTP_PORT_PREFERENCE for port in ports):
        score += 25
    return score


def _network_names(service: dict[str, Any]) -> list[str]:
    networks = list((service.get("networks") or {"default": None}).keys())
    return [name for name in networks if name != PROXY_NETWORK] + [
        PROXY_NETWORK
    ]


def _object_names(project: str, service: str) -> tuple[str, str]:
    role = re.sub(r"[^a-z0-9-]+", "-", service.lower()).strip("-") or "web"
    return f"{project}-{role}", role


def _resolved_labels(project: str, service: str, port: int) -> dict[str, str]:
    object_name, _ = _object_names(project, service)
    return {
        "traefik.enable": "true",
        "traefik.docker.network": PROXY_NETWORK,
        f"traefik.http.routers.{object_name}.entrypoints": "web",
        f"traefik.http.routers.{object_name}.rule": f"Host(`{project}.localhost`)",
        f"traefik.http.routers.{object_name}.service": object_name,
        f"traefik.http.routers.{object_name}-secure.entrypoints": "websecure",
        f"traefik.http.routers.{object_name}-secure.rule": (
            f"Host(`{project}.localhost`)"
        ),
        f"traefik.http.routers.{object_name}-secure.service": object_name,
        f"traefik.http.routers.{object_name}-secure.tls": "true",
        f"traefik.http.services.{object_name}.loadbalancer.server.port": str(port),
    }


def _dynamic_labels(project: str, service: str, port: int) -> dict[str, str]:
    resolved = _resolved_labels(project, service, port)
    _, role = _object_names("project", service)
    object_name = f"${{COMPOSE_PROJECT_NAME}}-{role}"
    values = [
        "traefik.enable=true",
        f"traefik.docker.network={PROXY_NETWORK}",
        (f"traefik.http.routers.{object_name}.entrypoints=web"),
        (
            f"traefik.http.routers.{object_name}.rule="
            "Host(`${COMPOSE_PROJECT_NAME}.localhost`)"
        ),
        (f"traefik.http.routers.{object_name}.service={object_name}"),
        (f"traefik.http.routers.{object_name}-secure.entrypoints=websecure"),
        (
            f"traefik.http.routers.{object_name}-secure.rule="
            "Host(`${COMPOSE_PROJECT_NAME}.localhost`)"
        ),
        (f"traefik.http.routers.{object_name}-secure.service={object_name}"),
        (f"traefik.http.routers.{object_name}-secure.tls=true"),
        (f"traefik.http.services.{object_name}.loadbalancer.server.port={port}"),
    ]
    return dict(zip(resolved, values, strict=True))


def _external_network(configuration: Any) -> bool:
    return isinstance(configuration, MutableMapping) and (
        configuration.get("external") is True
    ) and configuration.get("name", PROXY_NETWORK) == PROXY_NETWORK


def _model_labels(model: dict[str, Any]) -> list[tuple[str, str, str]]:
    labels = []
    for service_name, service in (model.get("services") or {}).items():
        if isinstance(service, MutableMapping):
            labels.extend(
                (service_name, key, value)
                for key, value in _label_pairs(service.get("labels"), None)
            )
    return labels


def _document_labels(
    document: CommentedMap, project_name: str
) -> list[tuple[str, str, str]]:
    labels = []
    services = document.get("services") or {}
    if not isinstance(services, MutableMapping):
        return labels
    for service_name, service in services.items():
        if not isinstance(service, MutableMapping):
            raise click.ClickException(
                f"existing override service '{service_name}' must be a mapping"
            )
        service_labels = service.get("labels")
        if service_labels is not None and not isinstance(
            service_labels, (MutableMapping, MutableSequence)
        ):
            raise click.ClickException(
                f"existing labels for service '{service_name}' cannot be "
                "inspected safely"
            )
        labels.extend(
            (str(service_name), key, value)
            for key, value in _label_pairs(service_labels, project_name)
        )
    return labels


def _label_pairs(labels: Any, project_name: str | None) -> list[tuple[str, str]]:
    if labels is None:
        return []
    if isinstance(labels, MutableMapping):
        pairs = [(str(key), _label_value(value)) for key, value in labels.items()]
    elif isinstance(labels, MutableSequence):
        pairs = []
        for label in labels:
            if not isinstance(label, str):
                raise click.ClickException(
                    "existing label sequences must contain only strings"
                )
            key, separator, value = label.partition("=")
            pairs.append((key, value if separator else ""))
    else:
        return []

    if project_name is None:
        return pairs
    project_reference = re.compile(
        r"(?<!\$)\$(?:\{COMPOSE_PROJECT_NAME\}|COMPOSE_PROJECT_NAME\b)"
    )
    return [
        (
            project_reference.sub(project_name, key),
            project_reference.sub(project_name, value),
        )
        for key, value in pairs
    ]


def _label_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return str(value).lower()
    return str(value)


def _validate_label_collisions(
    labels: list[tuple[str, str, str]],
    desired: dict[str, str],
    selected_service: str,
) -> None:
    desired_rule_key = next(key for key in desired if key.endswith(".rule"))
    desired_rule = desired[desired_rule_key]
    desired_rules = {
        key: value for key, value in desired.items() if key.endswith(".rule")
    }
    object_name = desired_rule_key.removeprefix(
        "traefik.http.routers."
    ).removesuffix(".rule")
    scoped_prefixes = (
        f"traefik.http.routers.{object_name}.",
        f"traefik.http.services.{object_name}.",
    )

    for service_name, key, value in labels:
        if service_name == selected_service:
            if key in desired and value != desired[key]:
                raise click.ClickException(
                    f"existing label '{key}' conflicts with the generated value"
                )
        elif key.startswith(scoped_prefixes):
            raise click.ClickException(
                f"existing label '{key}' is already defined for service "
                f"'{service_name}'"
            )

        if (
            key.endswith(".rule")
            and value in desired_rules.values()
            and (service_name != selected_service or key not in desired_rules)
        ):
            raise click.ClickException(
                f"existing router label '{key}' already uses {desired_rule}"
            )


def _yaml() -> YAML:
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)
    return yaml


def _next_backup(path: Path) -> Path:
    candidate = path.with_name(f"{path.name}.bak")
    counter = 1
    while candidate.exists() or candidate.is_symlink():
        candidate = path.with_name(f"{path.name}.bak.{counter}")
        counter += 1
    return candidate
